name: Script Workflow for Open Issues
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar dependencias de Actions
        run: npm install @actions/core @actions/github
        working-directory: .github/workflows/wf-issues
        
      - name: Comentar en el issue script
        run: node .github/workflows/wf-issues/wf-issues.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
